### ISSUE TITLE
Can the LWE matrix A not be selected randomly 

### ISSUE THREAD

**Issue by LBruyne** [ahenzinger/simplepir#2]
I wonder why the matrix should be randomly selected? Since D * A = H,  can I suppose that database (D) and the hint (H) is fixed and calculate A with A = D^-1 * H ? So that i can give a practical meaning by myself.

**Comment by LBruyne** [comment]
Or can we just give a fixed value to A

**Comment by ahenzinger** [comment]
We select A randomly since that is required for security to hold by the learning-with-errors assumption (see section 3.1 in https://eprint.iacr.org/2022/949.pdf). This is necessary because the LWE security may not hold for certain, bad A matrices.

In practice, we sample A to be a random matrix using a fixed hash function -- in the code, we use AES (called in rand.go).

**Comment by LBruyne** [comment]
> We select A randomly since that is required for security to hold by the learning-with-errors assumption (see section 3.1 in https://eprint.iacr.org/2022/949.pdf). This is necessary because the LWE problem may not hold for certain, bad A matrices.
> 
> In practice, we sample A to be a random matrix using a fixed hash function -- in the code, we use AES (called in rand.go).

I have seen your article before, wonderful work, that's a graceful framwork built upon the LWE assumption! 
But I have a simple idea that give some "meaningful" knowledge to the hint H, for example, the hint is a matrix $\in$ 
$\sqrt{N}$ *  $n$ that records some information for each row/column in the database, e.g. $h_i = \Sigma(D_i)$ where $D_i$ is the elements in ith row in the database. So that the server can calculate the matrix A by $A = D^{-1} * H$. The remain logic is as same as yours. I wonder if this A will be secure enough under the LWE assumption. Thank you for further answers!

**Comment by ahenzinger** [comment]
One interpretation of the hint H in SimplePIR (and DoublePIR) is that its entries are "random linear combinations" of the rows of the database D. In this sense, H can be thought of as a "hash" of D. 

I am not sure whether an A matrix computed as you suggest would be secure under the LWE assumption for any matrix D.

I hope this helps, and please let me know if you have any more questions.

**Comment by LBruyne** [comment]
Thanks for your answer. I'm considering a stronger property so called "verifiable", which introduced a malicious server that is willing to fool the client with fake data. 

In my reading of your paper, I observed that the matrix A seems a totally/pseodu randomly selected matrix. So if we give some verifiable property to the hint H, for example, each element in hint H is a commitment of the elements in each row of the database, that is,  $h_i = com(D_i)$, e.g.
$h_i = pedersonhash( D_{i0}, ... ,D_{in} )$ . Then the client can verify the PIR result, simply by checking the com of decrypted vector by comparing each element in H with the com he calculates with the decrypted response until he finds some $h_i = com(r)$. This states  that the result he got is turely a item in the database, rather than a fabricated thing from a malicious database server.
The question is, such a hint is related to the database D, as you suggested 

> H can be thought of as a "hash" of D

But now the matrix A is not randomly selected, because hint is fixed according to the database, the server can calculate the matrix A by $A = D^{-1} * H$. I'm wondering whether it will be secure under LWE assumption. 

What's more, in this case, the Hint H and the matrix A are all produced by the server. I question that whether it will be safe enough.

**Comment by LBruyne** [comment]
> One interpretation of the hint H in SimplePIR (and DoublePIR) is that its entries are "random linear combinations" of the rows of the database D. In this sense, H can be thought of as a "hash" of D.
> 
> I am not sure whether an A matrix computed as you suggest would be secure under the LWE assumption for any matrix D.
> 
> I hope this helps, and please let me know if you have any more questions.

I see. You mean we can view hint H as a multilinear extension of D

**Comment by ahenzinger** [comment]
That is a very interesting question! In terms of security, it seems okay to compute A = D^{-1} * H, as long as both D and H are "pseudorandom enough" (i.e., they are close to distributions with sufficient entropy). However, if A is chosen in this way, A will no longer be able to be represented by a succinct seed, and the server will need to send A to the client. So, it is not clear whether such an optimization would decrease the overall communication costs.

I hope this helps, and please let me know if you have any more questions.

**Comment by LBruyne** [comment]
Thank you for your work again. I will consider it a lot more~
